variables:
  AppDirectoryName: board_games_companion  

pr:
  - release

stages:

- stage: CI  
  jobs:
    - job: Build
      timeoutInMinutes: 20
      pool:
        vmImage: 'macOS-latest'

      steps:
      
        - task: FlutterInstall@0
          displayName: 'Install Flutter'
          inputs:
            channel: 'stable'
            version: 'custom'
            customVersion: '1.22.3'

        - task: FlutterBuild@0
          displayName: 'Build Android'
          inputs:
            target: 'aab'
            debugMode: true
            projectDirectory: '$(Build.SourcesDirectory)/$(AppDirectoryName)'
            buildNumber: '$(Build.BuildID)'
            buildName: '$(app.version).$(Build.BuildID)'

        - task: FlutterBuild@0
          displayName: 'Build iOS'
          inputs:
            target: 'ios'
            iosCodesign: false
            projectDirectory: '$(Build.SourcesDirectory)/$(AppDirectoryName)'
            buildNumber: '$(Build.BuildID)'
            buildName: '$(app.version).$(Build.BuildID)'