name: $(app.version).$(Build.BuildID)_$(SourceBranchName)

variables:
  AppDirectoryName: board_games_companion

pr:
  branches:
    include:
      - main

stages:
  - stage: CI
    jobs:
      - job: Build
        timeoutInMinutes: 20
        pool:
          vmImage: "macOS-latest"

        steps:
          - task: FlutterInstall@0
            displayName: "Install Flutter"
            inputs:
              mode: "auto"
              channel: "stable"
              version: "custom"
              customVersion: "2.5.2"

          - task: FlutterBuild@0
            displayName: "Build Android"
            inputs:
              target: "aab"
              debugMode: true
              projectDirectory: "$(Build.SourcesDirectory)/$(AppDirectoryName)"
              buildNumber: "$(Build.BuildID)"
              buildName: "$(app.version).$(Build.BuildID)"

          - task: FlutterBuild@0
            displayName: "Build iOS"
            inputs:
              target: "ios"
              debugMode: true
              iosCodesign: false
              projectDirectory: "$(Build.SourcesDirectory)/$(AppDirectoryName)"
              buildNumber: "$(Build.BuildID)"
              buildName: "$(app.version).$(Build.BuildID)"
