name: $(app.version).$(Build.BuildID) $(SourceBranchName)

variables:
  AppDirectoryName: BGC.Functions

pr:
  branches:
    include:
      - main

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - BGC.Functions

pool:
  vmImage: ubuntu-latest

steps:
  - task: UseDotNet@2
    displayName: Use .NET 6.0
    inputs:
      packageType: "sdk"
      version: "6.0.x"

  - script: |
      dotnet restore
      dotnet build -c Release
    displayName: Restore & Build
    workingDirectory: "$(Build.SourcesDirectory)/$(AppDirectoryName)"

  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: "publish"
      projects: "$(Build.SourcesDirectory)/$(AppDirectoryName)/*.csproj"
      arguments: "-c Release -o $(Build.ArtifactStagingDirectory)/out"
      publishWebProjects: false
      modifyOutputPath: false
      zipAfterPublish: false

  - task: ArchiveFiles@2
    displayName: "Zip"
    inputs:
      rootFolderOrFile: "$(Build.ArtifactStagingDirectory)/out"
      includeRootFolder: false
      archiveFile: "$(Build.ArtifactStagingDirectory)/out/$(app.version).$(Build.BuildID).zip"

  - task: PublishBuildArtifacts@1
    displayName: Publish Artifacts
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)/out/$(app.version).$(Build.BuildID).zip"
      ArtifactName: "drop"
      publishLocation: "Container"
