trigger:
  branches:
    include:
      - main

stages:
  - stage: DEV
    jobs:
      - job: PublishFunctions
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: AzureFunctionApp@1
            inputs:
              azureSubscription: 'bgc-dev(0b0b0e44-f48a-4f5b-9ee0-6bf6c571e58a)'
              appType: 'functionAppLinux'
              appName: 'bgc-func-dev'
              package: '$(System.DefaultWorkingDirectory)/**/*.zip'

  - stage: PROD
    jobs:
      - job: PublishFunctions
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: AzureFunctionApp@1
            inputs:
              azureSubscription: 'bgc-prod(637f5988-c385-408a-9b44-61b1c72f6b36)'
              appType: 'functionAppLinux'
              appName: 'bgc-func-prod'
              package: '$(System.DefaultWorkingDirectory)/**/*.zip'