<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-BGC.UpdateBoardGameCacheWorker-6fbee60d-5a99-4c79-9457-147dcaa4e3ef</UserSecretsId>   
    <DockerTargetOS>Linux</DockerTargetOS>    
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>    
    <DockerfileContext>..\..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity"  />
    <PackageReference Include="Azure.Messaging.ServiceBus"  />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus"  />
    <PackageReference Include="Microsoft.Extensions.Hosting"  />
    <PackageReference Include="Microsoft.Extensions.Http.Polly"  />    
    <PackageReference Include="Polly"  />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\BGC.Core\BGC.Core.csproj" />
    <ProjectReference Include="..\BGC.CacheCore\BGC.CacheCore.csproj" />
  </ItemGroup>
</Project>
