FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build

WORKDIR /source
COPY cache/BGC.UpdateBoardGameCacheWorker/*.csproj ./cache/BGC.UpdateBoardGameCacheWorker/
COPY cache/BGC.CacheCore/*.csproj ./cache/BGC.CacheCore/
COPY BGC.Core/*.csproj ./BGC.Core/

WORKDIR /source/cache/BGC.UpdateBoardGameCacheWorker
RUN dotnet restore

# TODO Remove this, to avoid including all of the files (especially the app settings)
COPY . ./
RUN dotnet publish cache/BGC.UpdateBoardGameCacheWorker/BGC.UpdateBoardGameCacheWorker.csproj --self-contained false -o /app

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "BGC.UpdateBoardGameCacheWorker.dll"]