parameters:
  workingDirectory:
  azureSpnConnectionName:
  sharedAzureSpnConnectionName:
  sharedStorageAccountName:
  sharedRecourceGroupName:
  terraformStateContainerName:
  terraformVersion:

steps:
  - checkout: self

  - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
    displayName: Installing Terraform v${{ parameters.terraformVersion }}
    condition: succeeded()
    inputs:
      terraformVersion: ${{ parameters.terraformVersion }}

  - task: TerraformTaskV4@4
    displayName: Terraform init
    condition: succeeded()
    inputs:
      provider: "azurerm"
      command: "init"
      workingDirectory: ${{ parameters.workingDirectory }}
      backendServiceArm: ${{ parameters.sharedAzureSpnConnectionName }}
      backendAzureRmResourceGroupName: ${{ parameters.sharedRecourceGroupName }}
      backendAzureRmStorageAccountName: ${{ parameters.sharedStorageAccountName }}
      backendAzureRmContainerName: ${{ parameters.terraformStateContainerName }}
      backendAzureRmKey: "terraform.tfstate"

  - task: TerraformTaskV4@4
    displayName: Terraform plan
    condition: succeeded()
    inputs:
      provider: "azurerm"
      command: "plan"
      workingDirectory: ${{ parameters.workingDirectory }}
      commandOptions: "-detailed-exitcode -input=false --var-file ./terraform.tfvars.json -out=tfplan"
      environmentServiceNameAzureRM: ${{ parameters.azureSpnConnectionName }}

  - task: TerraformTaskV4@4
    displayName: Terraform validate and apply
    condition: succeeded()
    inputs:
      provider: "azurerm"
      command: "apply"
      workingDirectory: ${{ parameters.workingDirectory }}
      commandOptions: "-input=false tfplan"
      environmentServiceNameAzureRM: ${{ parameters.azureSpnConnectionName }}
