name: $(Build.BuildID) $(SourceBranchName)

trigger: none

pr:
  branches:
    include:
      - main
  paths:
    include:
      - pipelines/infra
      - cloud_infrastructure

variables:
  - group: BGC-GLOBAL
  - name: terraformVersion
    value: $[variables['terraform.version']]
  - name: isMainBranch
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

stages:
  - stage: DEV
    variables:
      - group: BGC-DEV-INFRA
    jobs:
      - deployment: ProvisionAzureResources
        displayName: Provision Azure Resources
        environment: DEV
        strategy:
          runOnce:
            deploy:
              steps:
                - template: azure-resource-provisioning-template.yml
                  parameters:
                    workingDirectory: $(System.DefaultWorkingDirectory)/cloud_infrastructure/terraform/dev
                    azureSpnConnectionName: bgc-dev
                    azureSpnConnectionId: e3fc2d39-5f38-4743-beee-0186ad98d553
                    resourceGroupName: $(resourceGroupName)
                    storageAccountName: $(storageAccountName)
                    terraformVersion: $(terraformVersion)
  - stage: PROD
    condition: and(succeeded(), eq(variables.isMainBranch, 'true'))
    variables:
      - group: BGC-PROD-INFRA
    jobs:
      - deployment: ProvisionAzureResources
        displayName: Provision Azure Resources
        environment: PROD
        strategy:
          runOnce:
            deploy:
              steps:
                - template: azure-resource-provisioning-template.yml
                  parameters:
                    workingDirectory: $(System.DefaultWorkingDirectory)/cloud_infrastructure/terraform/prod
                    azureSpnConnectionName: bgc-prod
                    azureSpnConnectionId: 909c51d2-a2f4-4c09-85f9-2f4985afe4c6
                    resourceGroupName: $(resourceGroupName)
                    storageAccountName: $(storageAccountName)
                    terraformVersion: $(terraformVersion)
