resources:
  pipelines:
    - pipeline: Search-API-CI
      source: "Search API CI"
      trigger:
        branches:
          include:
            - main

trigger: none

pool:
  vmImage: ubuntu-22.04
  workspace:
    clean: all

parameters:
  - name: buildId
    displayName: Build ID
    type: string
    default: ""

variables:
  # General
  acrName: bgcsharedcr
  acrServer: bgcsharedcr.azurecr.io
  acrServiceRepositoryName: bgc

  registryUrl: registry.hub.docker.com
  registryName: mkieres
  registryRepositoryName: bgc

  # Dev
  armServiceConnectionDev: bgc-dev
  resourceGroupNameDev: bgc-dev-rg
  azureContainerAppNameDev: bgc-search-service-dev-ca

  # Prod
  armServiceConnectionProd: bgc-prod
  resourceGroupNameProd: bgc-prod-rg
  azureContainerAppNameProd: bgc-search-service-prod-ca

  deployTagId: $[coalesce('${{ parameters.buildId }}', variables['resources.pipeline.Search-API-CI.runID'])]

stages:
  - stage: DEV
    jobs:
      - deployment: DeployDev
        variables:
          - group: BGC-SEARCH-API-SHARED
          - group: BGC-SEARCH-API-DEV
        environment: DEV
        strategy:
          runOnce:
            deploy:
              steps:
                - download: none

                - task: PowerShell@2
                  displayName: Set build name
                  inputs:
                    targetType: "inline"
                    script: |
                      [string] $releaseName = "$(deployTagId)"
                      Write-Host "Setting the name of the build to '$releaseName'."
                      Write-Host "##vso[build.updatebuildnumber]$releaseName"

                - template: ${{ variables['System.DefaultWorkingDirectory'] }}/pipelines/templates/update_container_secrets.yaml
                  parameters:
                    armServiceConnection: $(armServiceConnectionDev)
                    containerAppName: $(azureContainerAppNameDev)
                    resourceGroupName: $(resourceGroupNameDev)

                - task: AzureCLI@2
                  displayName: Deploy Docker image to Container App
                  continueOnError: true
                  inputs:
                    azureSubscription: $(armServiceConnectionDev)
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      az containerapp registry set -n $(azureContainerAppNameDev) -g $(resourceGroupNameDev) --server registry.hub.docker.com --username  $(registryUsername) --password $(registryPassword)
                      az containerapp update -n $(azureContainerAppNameDev) -g $(resourceGroupNameDev) --image $(registryName)/$(registryRepositoryName):$(deployTagId) --set-env-vars AppSettings__MongoDbSettings__ConnectionString=secretref:mongodb-connection AppSettings__ApiKeyAuthenticationSettings__ApiKey=secretref:api-key KeyVaultName=$(keyVaultName)

  - stage: PROD
    dependsOn: DEV
    jobs:
      - deployment: DeployProd
        variables:
          - group: BGC-SEARCH-API-SHARED
          - group: BGC-SEARCH-API-PROD
        environment: PROD
        strategy:
          runOnce:
            deploy:
              steps:
                - download: none

                - template: ${{ variables['System.DefaultWorkingDirectory'] }}/pipelines/templates/update_container_secrets.yaml
                  parameters:
                    armServiceConnection: $(armServiceConnectionProd)
                    containerAppName: $(azureContainerAppNameProd)
                    resourceGroupName: $(resourceGroupNameProd)

                - task: AzureCLI@2
                  displayName: Deploy Docker image to Container App
                  continueOnError: true
                  inputs:
                    azureSubscription: $(armServiceConnectionProd)
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      az containerapp registry set -n $(azureContainerAppNameProd) -g $(resourceGroupNameProd) --server registry.hub.docker.com --username  $(registryUsername) --password $(registryPassword)
                      az containerapp update -n $(azureContainerAppNameProd) -g $(resourceGroupNameProd) --image $(registryName)/$(registryRepositoryName):$(deployTagId) --set-env-vars AppSettings__MongoDbSettings__ConnectionString=secretref:mongodb-connection AppSettings__ApiKeyAuthenticationSettings__ApiKey=secretref:api-key KeyVaultName=$(keyVaultName)

                - task: git-tag-on-release-task@9
                  displayName: Tag Artifacts
                  inputs:
                    staticTagName: $(deployTagId)
