<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>    
    <UserSecretsId>495d1e9c-fe6c-46e3-8723-b99354f34ef1</UserSecretsId>    
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Messaging.ServiceBus"  />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi"  />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory"  />
    <PackageReference Include="Microsoft.Extensions.Hosting"  />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions"  />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations"  />
    <PackageReference Include="MongoDB.Driver"  />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol"  />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting"  />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore"  />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http"  />
    <PackageReference Include="Polly"  />
    <PackageReference Include="Serilog.AspNetCore"  />
    <PackageReference Include="Serilog.Sinks.OpenTelemetry"  />
    <PackageReference Include="StyleCop.Analyzers" >
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore"  />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BGC.Core\BGC.Core.csproj" />
  </ItemGroup>

</Project>
