FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 8080
EXPOSE 443

# Install curl for health checks
RUN apt-get update && apt-get install -y curl

# This stage is used to build the service project
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
ARG BUILD_CONFIGURATION
WORKDIR /src
COPY ["BGC.SearchApi/BGC.SearchApi.csproj", "BGC.SearchApi/"]
COPY ["BGC.Core/BGC.Core.csproj", "BGC.Core/"]
RUN dotnet restore "./BGC.SearchApi/BGC.SearchApi.csproj"
COPY . .
WORKDIR "/src/BGC.SearchApi"
RUN dotnet build "./BGC.SearchApi.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION
RUN dotnet publish "./BGC.SearchApi.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "BGC.SearchApi.dll"]

FROM base AS debug
# Install the vsdbg debugger for remote debugging because for some reason is not copied across by vs code automatically
RUN apt-get update && \
    apt-get install -y curl unzip && \
    curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l /remote_debugger

WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "BGC.SearchApi.dll"]