FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /source
COPY *.csproj .

RUN dotnet restore

COPY . .
RUN dotnet publish -self-contained false --no-restore -o /app

FROM alpine:3.14
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "BGC.SearchApi.dll"]