@hostname=localhost
@port=7226

GET https://{{hostname}}:{{port}}/api/search?query=splendor
X-Api-Key: whatever

###

GET https://{{hostname}}:{{port}}/api/search?query=heat
X-Api-Key: whatever

###

GET https://{{hostname}}:{{port}}/api/search?query=My Little Scythe

###

GET https://bgc-search-service-dev-ca.graytree-d4bbc196.eastus.azurecontainerapps.io/api/search?query=scythe
Ocp-Apim-Subscription-Key: <key>