@hostname=localhost
@port=55383

@ApiKey=must_match_with_whats_in_settings

### root

GET https://{{hostname}}:{{port}}/api/search?query=root
X-Api-Key: {{ApiKey}}

### Splendor

GET https://{{hostname}}:{{port}}/api/search?query=splendor
X-Api-Key: {{ApiKey}}

### Heat

GET https://{{hostname}}:{{port}}/api/search?query=heat
X-Api-Key: {{ApiKey}}

### Smallworld

GET https://{{hostname}}:{{port}}/api/search?query=smallworld
X-Api-Key: {{ApiKey}}

### My Little Scythe

GET https://{{hostname}}:{{port}}/api/search?query=My%20Little%20Scythe
X-Api-Key: {{ApiKey}}

### 

GET https://bgc-shared-apim.azure-api.net/dev/api/search?query=root
Ocp-Apim-Subscription-Key: <subscription_key_get_from_APIM>