name: board_games_companion
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  logger: ^0.9.4
  dio_http_cache: ^0.2.6
  dio_http2_adapter: ^1.0.0
  cached_network_image: ^2.0.0
  firebase_core: ^0.5.0+1
  firebase_crashlytics: ^0.2.1+1
  firebase_analytics: 6.3.0
  hive: ^1.4.1+1  
  hive_flutter: ^0.3.0+2
  path_provider: ^1.6.5
  polygon_clipper: ^1.0.2
  async: ^2.4.0
  uuid: ^2.0.4
  image_picker: ^0.6.7+1
  xml: ^3.6.1
  provider: ^4.0.4
  animations: ^1.1.2
  intl: ^0.16.1
  collection: any # ^1.14.11
  url_launcher: ^5.4.2
  package_info: ^0.4.0+16
  google_fonts: ^1.0.0
  html_unescape: ^1.0.1+3
  in_app_review: ^1.0.4
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  analyzer: ^0.40.4
  hive_generator: 0.8.1
  build_runner: ^1.8.0
  flutter_launcher_icons: "^0.7.3"
  flutter_test:
    sdk: flutter

# TODO Workaround for pub get issues. Follow https://github.com/hivedb/hive/issues/268 to see what's the actual fix
dependency_overrides:
  path: ^1.6.4
  dartx: ^0.4.0
  collection: any


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/
   - assets/icons/
   - assets/flags/
   - google_fonts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
