<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Azure.Identity"  />
    <PackageReference Include="Azure.Messaging.ServiceBus"  />    
    <PackageReference Include="Microsoft.Extensions.Http.Polly"  />
    <PackageReference Include="Polly"  />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\BGC.Core\BGC.Core.csproj" />
  </ItemGroup>

</Project>
