<Project Sdk="Microsoft.NET.Sdk">   
  <PropertyGroup>    
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Moq" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BGC.Core\BGC.Core.csproj" />
  </ItemGroup>

</Project>
